spring:
  application:
    name: zuul-service
  cloud:
    config:
      enabled: true

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: false


zuul:
  routes:
    po:
      path: /poo/**
      serivce-id: po
    pc:
      path: /pcc/**
      service-id: pc