#spring:
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: inputSubscriber
#      default:
#        contentType: application/json


spring:
  cloud:
    stream:
      default:
        contentType: application/json
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
#        input:
#          binder: kafka
#          destination: test
#          content-type: text/plain
#          group: input-group-1
        output:
          binder: kafka
          destination: inputSubscriber
          group: groupId
          content-type: application/json
